### PR TITLE
Changed OIN Acronym to OPLN

### PR DESCRIPTION
**Pull request by Mentors4EDU**

### CODE REVIEW

**Comment by goneall** [comment]
@Mentors4EDU I noticed that this PR is against a test repo rather than against the LicenseList-XML repo.

Did you use the tools.spdx.org to submit the PR?  If so, there is probably something miss-configured.  Let me know and I can attempt a fix.

**Comment by Mentors4EDU** [comment]
@goneall Actually I believe I have. I typed master branch in the form and for some reason it did it to the test branch. Maybe you can help make the request for me?

**Comment by goneall** [comment]
> Actually I believe I have. I typed master branch in the form and for some reason it did it to the test branch. Maybe you can help make the request for me?

I suspect there is a configuration problem with the app - I'll go ahead and add the PR to the main application manually and fix the app so that in the future, it will update the correct branch.  It will probably take me a day or two to complete.

**Comment by Mentors4EDU** [comment]
> > Actually I believe I have. I typed master branch in the form and for some reason it did it to the test branch. Maybe you can help make the request for me?
> 
> I suspect there is a configuration problem with the app - I'll go ahead and add the PR to the main License-List-XML repo manually and fix the app so that in the future, it will update the correct branch. It will probably take me a day or two to complete.

Yes, that would be great. Thank you for your help!

**Comment by goneall** [comment]
@Mentors4EDU Submitted PR https://github.com/spdx/license-list-XML/pull/1163

Also found the issue with the online tools - resolved with PR https://github.com/spdx/spdx-online-tools/pull/278

**Pull request closed without merging**
